name: 'Label Command'
description: 'Label Issues and PRs with commands'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true
  config-file:
    description: 'Name of config-file. Defaults to label-commands.json.'
    default: label-commands.json
    required: false
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'search'  
  color: 'gray-dark'
