name: build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    uses: ckotzbauer/actions-toolkit/.github/workflows/toolkit-build-test.yml@v0.42.1
    with:
      install-node: true
      build-commands: |
        npm ci
        npm run package
      test-commands: npm test
